Repository OCA/l10n-thailand, pull requests merged in 2020-10, with the labels that each got.

#168 [FIX] l10n_th_base_location : test script
  l10n_th_base_location/tests/test_base_location.py
Labels: bot is merging ⏳

#152 [FIX] tax report, to show negative for refund
  l10n_th_tax_report/reports/tax_report.xml
  l10n_th_tax_report/reports/tax_report_xlsx.py
Labels: approved, bot is merging ⏳

#143 [13.0][ADD] l10n_th_fonts
  l10n_th_fonts/README.rst
  l10n_th_fonts/__init__.py
  l10n_th_fonts/__manifest__.py
  l10n_th_fonts/models/__init__.py
  l10n_th_fonts/models/res_company.py
  l10n_th_fonts/readme/CONFIGURE.rst
  l10n_th_fonts/readme/CONTRIBUTORS.rst
  l10n_th_fonts/readme/DESCRIPTION.rst
  l10n_th_fonts/static/description/index.html
  l10n_th_fonts/static/fonts/AngsanaNew.ttf
  l10n_th_fonts/static/fonts/THSarabunNew.ttf
  l10n_th_fonts/static/scss/fonts_style.scss
  l10n_th_fonts/views/report_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#175 [13.0][IMP] l10n_th_tax_invoice, add ondelete='restrict' on partner_id
  l10n_th_tax_invoice/models/account_move.py
Labels: bot is merging ⏳

#170 [13.0][IMP] l10n_th_tax_invoice, late tax report up to 6 months
  l10n_th_tax_invoice/models/account_move.py
  l10n_th_tax_invoice/tests/test_tax_invoice.py
  l10n_th_tax_invoice/views/account_move_view.xml
  l10n_th_tax_report/reports/tax_report.py
Labels: approved, bot is merging ⏳, ready to merge

#180 [13.0][FIX] l10n_th_tax_invoice, do not delete sum-zero move lines
  l10n_th_tax_invoice/models/account_move.py
Labels: bot is merging ⏳

#179 [13.0][FIX] test script UserError import not thai
  l10n_th_base_location/tests/test_base_location.py
Labels: approved, bot is merging ⏳

#169 [13.0][FIX] l10n_th_partner: change field's name
  l10n_th_partner/models/res_partner.py
  l10n_th_partner/views/res_partner_view.xml
Labels: bot is merging ⏳

#181 [FIX] l10n_th_vat_report : delete abs on excel report
  l10n_th_vat_report/reports/vat_report_xlsx.py
Labels: bot is merging ⏳

#173 [13.0][FIX] l10n_th_withholding_tax_report - Improved Code
  l10n_th_withholding_tax_report/README.rst
  l10n_th_withholding_tax_report/__manifest__.py
  l10n_th_withholding_tax_report/data/report_data.xml
  l10n_th_withholding_tax_report/models/__init__.py
  l10n_th_withholding_tax_report/models/report_withholding_tax.py
  l10n_th_withholding_tax_report/readme/DESCRIPTION.rst
  l10n_th_withholding_tax_report/readme/USAGE.rst
  l10n_th_withholding_tax_report/report/__init__.py
  l10n_th_withholding_tax_report/report/report_withholding_tax_qweb.xml
  l10n_th_withholding_tax_report/report/report_withholding_tax_xlsx.py
  l10n_th_withholding_tax_report/static/description/index.html
  l10n_th_withholding_tax_report/templates/layouts.xml
  l10n_th_withholding_tax_report/templates/report_template.xml
  l10n_th_withholding_tax_report/tests/__init__.py
  l10n_th_withholding_tax_report/tests/date_range_test_data.xml
  l10n_th_withholding_tax_report/tests/test_wht_cert_report.py
  l10n_th_withholding_tax_report/tests/test_wt_cert_report.py
  l10n_th_withholding_tax_report/views/menu.xml
  l10n_th_withholding_tax_report/wizard/withholding_tax_report_wizard_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#182 [14.0][MIG] l10n_th_amount_to_text
  l10n_th_amount_to_text/README.rst
  l10n_th_amount_to_text/__init__.py
  l10n_th_amount_to_text/__manifest__.py
  l10n_th_amount_to_text/i18n/l10n_th_amount_to_text.pot
  l10n_th_amount_to_text/i18n/th.po
  l10n_th_amount_to_text/models/__init__.py
  l10n_th_amount_to_text/models/res_currency.py
  l10n_th_amount_to_text/readme/CONFIGURE.rst
  l10n_th_amount_to_text/readme/CONTRIBUTORS.rst
  l10n_th_amount_to_text/readme/DESCRIPTION.rst
  l10n_th_amount_to_text/readme/USAGE.rst
  l10n_th_amount_to_text/static/description/icon.png
  l10n_th_amount_to_text/static/description/index.html
  l10n_th_amount_to_text/tests/__init__.py
  l10n_th_amount_to_text/tests/test_amount_to_text.py
  setup/l10n_th_amount_to_text/odoo/addons/l10n_th_amount_to_text
  setup/l10n_th_amount_to_text/setup.py
Labels: bot is merging ⏳

#184 [13.0][FIX] withholding_tax test script
  l10n_th_withholding_tax/security/ir.model.access.csv
  l10n_th_withholding_tax/tests/account_withholding_tax_test.xml
  l10n_th_withholding_tax/tests/test_withholding_tax.py
  l10n_th_withholding_tax_cert/models/__init__.py
  l10n_th_withholding_tax_cert/models/account.py
  l10n_th_withholding_tax_cert/tests/account_withholding_tax_test.xml
  l10n_th_withholding_tax_cert/tests/test_wt_cert.py
  l10n_th_withholding_tax_multi/README.rst
  l10n_th_withholding_tax_multi/models/account_payment.py
  l10n_th_withholding_tax_multi/readme/USAGE.rst
  l10n_th_withholding_tax_multi/static/description/index.html
  l10n_th_withholding_tax_multi/tests/account_withholding_tax_test.xml
  l10n_th_withholding_tax_multi/tests/test_withholding_tax_multi.py
Labels: bot is merging ⏳
