Repository OCA/l10n-thailand, pull requests merged in 2020-11, with the labels that each got.

#196 [FIX] l10n_th_withholding_tax, error on _compute_wt_tax_id method
  l10n_th_withholding_tax/models/account_move.py
Labels: bot is merging ⏳

#199 [13.0][ENH] l10n_th_withholding_tax_cert, use service action to call create cert
  l10n_th_withholding_tax_cert/models/withholding_tax_cert.py
  l10n_th_withholding_tax_cert/tests/test_wt_cert.py
  l10n_th_withholding_tax_cert/wizard/create_withholding_tax_cert.xml
Labels: bot is merging ⏳

#200 [13.0][ENH] l10n_th_withholding_tax_cert, add create multi certs
  l10n_th_withholding_tax_cert/__manifest__.py
  l10n_th_withholding_tax_cert/models/withholding_tax_cert.py
  l10n_th_withholding_tax_cert/readme/HISTORY.rst
  l10n_th_withholding_tax_cert/readme/USAGE.rst
  l10n_th_withholding_tax_cert/tests/test_wt_cert.py
  l10n_th_withholding_tax_cert/views/withholding_tax_cert.xml
  l10n_th_withholding_tax_cert/wizard/create_withholding_tax_cert.py
  l10n_th_withholding_tax_cert/wizard/create_withholding_tax_cert.xml
Labels: bot is merging ⏳

#205 [13.0][ENH] l10n_th_tax_invoice, to support case journal entry
  l10n_th_tax_invoice/models/account_move.py
Labels: bot is merging ⏳

#204 [13.0][FIX] l10n_th_withholding_tax_cert_form : domain groupby wt_lines
  l10n_th_withholding_tax_cert_form/models/withholding_tax_cert.py
Labels: bot is merging ⏳

#198 [13.0][ADD] l10n_th_promptpay
  l10n_th_promptpay/__init__.py
  l10n_th_promptpay/__manifest__.py
  l10n_th_promptpay/data/payment_icon_data.xml
  l10n_th_promptpay/i18n/l10n_th_promptpay.pot
  l10n_th_promptpay/i18n/th_TH.po
  l10n_th_promptpay/models/__init__.py
  l10n_th_promptpay/models/payment.py
  l10n_th_promptpay/readme/CONTRIBUTORS.rst
  l10n_th_promptpay/readme/CREDITS.rst
  l10n_th_promptpay/readme/DESCRIPTION.rst
  l10n_th_promptpay/readme/HISTORY.rst
  l10n_th_promptpay/readme/USAGE.rst
  l10n_th_promptpay/static/description/icon.png
  l10n_th_promptpay/static/description/promptpay_QR_code.png
  l10n_th_promptpay/static/description/promptpay_configuration.png
  l10n_th_promptpay/static/description/website_confirm_order.png
  l10n_th_promptpay/static/img/baac.png
  l10n_th_promptpay/static/img/bay.png
  l10n_th_promptpay/static/img/bbl.png
  l10n_th_promptpay/static/img/bnp.png
  l10n_th_promptpay/static/img/boa.png
  l10n_th_promptpay/static/img/cacib.png
  l10n_th_promptpay/static/img/cimb.png
  l10n_th_promptpay/static/img/citi.png
  l10n_th_promptpay/static/img/db.png
  l10n_th_promptpay/static/img/ghb.png
  l10n_th_promptpay/static/img/gsb.png
  l10n_th_promptpay/static/img/hsbc.png
  l10n_th_promptpay/static/img/ibank.png
  l10n_th_promptpay/static/img/icbc.png
  l10n_th_promptpay/static/img/jpm.png
  l10n_th_promptpay/static/img/kbank.png
  l10n_th_promptpay/static/img/kk.png
  l10n_th_promptpay/static/img/ktb.png
  l10n_th_promptpay/static/img/lhb.png
  l10n_th_promptpay/static/img/mb.png
  l10n_th_promptpay/static/img/mega.png
  l10n_th_promptpay/static/img/mufg.png
  l10n_th_promptpay/static/img/promptpay_logo.png
  l10n_th_promptpay/static/img/rbs.png
  l10n_th_promptpay/static/img/sc.png
  l10n_th_promptpay/static/img/scb.png
  l10n_th_promptpay/static/img/smbc.png
  l10n_th_promptpay/static/img/tbank.png
  l10n_th_promptpay/static/img/tcrb.png
  l10n_th_promptpay/static/img/thai_qr_payment.png
  l10n_th_promptpay/static/img/tisco.png
  l10n_th_promptpay/static/img/tmb.png
  l10n_th_promptpay/static/img/uob.png
  l10n_th_promptpay/views/payment_transfer_acquirer_form.xml
  l10n_th_promptpay/views/payment_views.xml
  requirements.txt
  setup/l10n_th_promptpay/odoo/addons/l10n_th_promptpay
  setup/l10n_th_promptpay/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#193 [FIX] l10n_th_amount_to_text - word in config readme file
  l10n_th_amount_to_text/README.rst
  l10n_th_amount_to_text/__manifest__.py
  l10n_th_amount_to_text/readme/CONFIGURE.rst
  l10n_th_amount_to_text/static/description/index.html
Labels: approved, ready to merge

#210 [13.0][IMP] l10n_th_tax_invoice, Allow move reset draft
  l10n_th_tax_invoice/models/account_move.py
  l10n_th_tax_invoice/models/account_payment.py
  l10n_th_tax_invoice/tests/test_tax_invoice.py
  l10n_th_tax_invoice/views/account_payment_view.xml
Labels: bot is merging ⏳
