Repository OCA/l10n-thailand, pull requests merged in 2020-08, with the labels that each got.

#161 [IMP] data code thai address
  l10n_th_base_location/data/TH_en.txt
  l10n_th_base_location/data/TH_th.txt
  l10n_th_base_location/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#159 [13.0][ENH]l10n_th_withholding_tax_report
  l10n_th_withholding_tax_report/readme/CONTRIBUTORS.rst
  l10n_th_withholding_tax_report/report/report_withholding_tax.py
  l10n_th_withholding_tax_report/wizard/withholding_tax_report_wizard.py
  l10n_th_withholding_tax_report/wizard/withholding_tax_report_wizard_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#166 [13.0][FIX] l10n_th_tax_invoice, unlink move_line when same partner only
  l10n_th_tax_invoice/models/account_move.py
Labels: bot is merging ⏳

#153 [ADD] l10n_th_expense_tax_invoice
  l10n_th_expense_tax_invoice/__init__.py
  l10n_th_expense_tax_invoice/__manifest__.py
  l10n_th_expense_tax_invoice/models/__init__.py
  l10n_th_expense_tax_invoice/models/account_move.py
  l10n_th_expense_tax_invoice/models/hr_expense.py
  l10n_th_expense_tax_invoice/readme/CONTRIBUTORS.rst
  l10n_th_expense_tax_invoice/readme/DESCRIPTION.rst
  l10n_th_expense_tax_invoice/static/description/icon.png
  l10n_th_expense_tax_invoice/static/description/index.html
  l10n_th_expense_tax_invoice/tests/__init__.py
  l10n_th_expense_tax_invoice/tests/test_expense_tax_invoice.py
  l10n_th_expense_tax_invoice/views/hr_expense_view.xml
  setup/l10n_th_expense_tax_invoice/odoo/addons/l10n_th_expense_tax_invoice
  setup/l10n_th_expense_tax_invoice/setup.py
Labels: bot is merging ⏳

#167 [13.0][FIX] l10n_th_tax_invoice, error reconcile invoice/refund with undue vat
  l10n_th_tax_invoice/models/account_move.py
  l10n_th_tax_invoice/tests/test_tax_invoice.py
Labels: approved, bot is merging ⏳

#157 [12.0][ENH] l10n_th_vendor_tax_invoice to apply with tax sequence
  l10n_th_vat_report/reports/vat_report.py
  l10n_th_vat_report/reports/vat_report.xml
  l10n_th_vendor_tax_invoice/models/__init__.py
  l10n_th_vendor_tax_invoice/models/account.py
  l10n_th_vendor_tax_invoice/models/account_invoice.py
  l10n_th_vendor_tax_invoice/models/account_move.py
  l10n_th_vendor_tax_invoice/views/account_view.xml
Labels: approved, bot is merging ⏳
