Repository OCA/l10n-thailand, pull requests merged in 2022-11, with the labels that each got.

#317 [FIX] update copier template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#240 [14.0][ADD] l10n_th_gov_purchase_guarantee
  l10n_th_gov_purchase_guarantee/README.rst
  l10n_th_gov_purchase_guarantee/__init__.py
  l10n_th_gov_purchase_guarantee/__manifest__.py
  l10n_th_gov_purchase_guarantee/data/ir_sequence_data.xml
  l10n_th_gov_purchase_guarantee/data/purchase_guarantee_method_data.xml
  l10n_th_gov_purchase_guarantee/data/purchase_guarantee_type_data.xml
  l10n_th_gov_purchase_guarantee/models/__init__.py
  l10n_th_gov_purchase_guarantee/models/account_move.py
  l10n_th_gov_purchase_guarantee/models/purchase_guarantee.py
  l10n_th_gov_purchase_guarantee/models/purchase_guarantee_method.py
  l10n_th_gov_purchase_guarantee/models/purchase_guarantee_type.py
  l10n_th_gov_purchase_guarantee/models/purchase_order.py
  l10n_th_gov_purchase_guarantee/models/purchase_requisition.py
  l10n_th_gov_purchase_guarantee/readme/CONFIGURATION.rst
  l10n_th_gov_purchase_guarantee/readme/CONTRIBUTORS.rst
  l10n_th_gov_purchase_guarantee/readme/DESCRIPTION.rst
  l10n_th_gov_purchase_guarantee/security/ir.model.access.csv
  l10n_th_gov_purchase_guarantee/security/purchase_guarantee_security.xml
  l10n_th_gov_purchase_guarantee/static/description/icon.png
  l10n_th_gov_purchase_guarantee/static/description/index.html
  l10n_th_gov_purchase_guarantee/tests/__init__.py
  l10n_th_gov_purchase_guarantee/tests/test_purchase_guarantee.py
  l10n_th_gov_purchase_guarantee/views/account_move_views.xml
  l10n_th_gov_purchase_guarantee/views/purchase_guarantee_method_views.xml
  l10n_th_gov_purchase_guarantee/views/purchase_guarantee_type_views.xml
  l10n_th_gov_purchase_guarantee/views/purchase_guarantee_views.xml
  l10n_th_gov_purchase_guarantee/views/purchase_order_views.xml
  l10n_th_gov_purchase_guarantee/views/purchase_requisition_views.xml
  l10n_th_gov_purchase_guarantee/wizards/__init__.py
  l10n_th_gov_purchase_guarantee/wizards/account_payment_register.py
  setup/l10n_th_gov_purchase_guarantee/odoo/addons/l10n_th_gov_purchase_guarantee
  setup/l10n_th_gov_purchase_guarantee/setup.py
Labels: approved, work in progress, ready to merge, bot is merging ⏳

#314 [14.0][ADD] l10n_th_gov_purchase_request
  l10n_th_gov_purchase_request/README.rst
  l10n_th_gov_purchase_request/__init__.py
  l10n_th_gov_purchase_request/__manifest__.py
  l10n_th_gov_purchase_request/data/procurement_method.xml
  l10n_th_gov_purchase_request/data/procurement_type.xml
  l10n_th_gov_purchase_request/data/purchase_request_exception.xml
  l10n_th_gov_purchase_request/data/purchase_request_substate.xml
  l10n_th_gov_purchase_request/data/purchase_type.xml
  l10n_th_gov_purchase_request/models/__init__.py
  l10n_th_gov_purchase_request/models/procurement_committee.py
  l10n_th_gov_purchase_request/models/procurement_method.py
  l10n_th_gov_purchase_request/models/procurement_type.py
  l10n_th_gov_purchase_request/models/purchase_request.py
  l10n_th_gov_purchase_request/models/purchase_request_line.py
  l10n_th_gov_purchase_request/models/purchase_type.py
  l10n_th_gov_purchase_request/readme/CONFIGURATION.rst
  l10n_th_gov_purchase_request/readme/CONTRIBUTORS.rst
  l10n_th_gov_purchase_request/readme/DESCRIPTION.rst
  l10n_th_gov_purchase_request/security/ir.model.access.csv
  l10n_th_gov_purchase_request/security/procurement_team.xml
  l10n_th_gov_purchase_request/static/description/icon.png
  l10n_th_gov_purchase_request/static/description/index.html
  l10n_th_gov_purchase_request/tests/__init__.py
  l10n_th_gov_purchase_request/tests/test_gov_purchase_request.py
  l10n_th_gov_purchase_request/views/procurement_method_views.xml
  l10n_th_gov_purchase_request/views/procurement_type_views.xml
  l10n_th_gov_purchase_request/views/purchase_request_views.xml
  l10n_th_gov_purchase_request/views/purchase_type_views.xml
  l10n_th_gov_purchase_request/wizards/__init__.py
  l10n_th_gov_purchase_request/wizards/purchase_request_line_make_purchase_requisition.py
  setup/l10n_th_gov_purchase_request/odoo/addons/l10n_th_gov_purchase_request
  setup/l10n_th_gov_purchase_request/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#318 [FIX] update copier template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: bot is merging ⏳

#320 [UPD] copier v16.0
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#254 [14.0][ADD] l10n_th_account_asset_management
  l10n_th_account_asset_management/README.rst
  l10n_th_account_asset_management/__init__.py
  l10n_th_account_asset_management/__manifest__.py
  l10n_th_account_asset_management/models/__init__.py
  l10n_th_account_asset_management/models/account_asset.py
  l10n_th_account_asset_management/models/account_asset_line.py
  l10n_th_account_asset_management/readme/CONTRIBUTORS.rst
  l10n_th_account_asset_management/readme/DESCRIPTION.rst
  l10n_th_account_asset_management/report/__init__.py
  l10n_th_account_asset_management/report/account_asset_report_xls.py
  l10n_th_account_asset_management/static/description/icon.png
  l10n_th_account_asset_management/static/description/index.html
  l10n_th_account_asset_management/tests/__init__.py
  l10n_th_account_asset_management/tests/test_account_asset_management.py
  l10n_th_account_asset_management/tests/test_asset_management_xls.py
  l10n_th_account_asset_management/views/account_asset_views.xml
  setup/l10n_th_account_asset_management/odoo/addons/l10n_th_account_asset_management
  setup/l10n_th_account_asset_management/setup.py
Labels: bot is merging ⏳, stale

#296 [15.0][MIG] l10n_th_base_location
  l10n_th_base_location/README.rst
  l10n_th_base_location/__init__.py
  l10n_th_base_location/__manifest__.py
  l10n_th_base_location/data/TH_en.txt
  l10n_th_base_location/data/TH_th.txt
  l10n_th_base_location/demo/TH_en.txt
  l10n_th_base_location/demo/TH_th.txt
  l10n_th_base_location/i18n/base_location_thailand.pot
  l10n_th_base_location/i18n/l10n_th_base_location.pot
  l10n_th_base_location/i18n/th.po
  l10n_th_base_location/models/__init__.py
  l10n_th_base_location/models/res_city_zip.py
  l10n_th_base_location/models/res_company.py
  l10n_th_base_location/models/res_country_state.py
  l10n_th_base_location/models/res_partner.py
  l10n_th_base_location/readme/CONTRIBUTORS.rst
  l10n_th_base_location/readme/CREDITS.rst
  l10n_th_base_location/readme/DESCRIPTION.rst
  l10n_th_base_location/readme/INSTALL.rst
  l10n_th_base_location/readme/USAGE.rst
  l10n_th_base_location/static/description/icon.png
  l10n_th_base_location/static/description/index.html
  l10n_th_base_location/tests/__init__.py
  l10n_th_base_location/tests/test_base_location.py
  l10n_th_base_location/views/res_city_zip_view.xml
  l10n_th_base_location/wizard/__init__.py
  l10n_th_base_location/wizard/geonames_import.py
  l10n_th_base_location/wizard/geonames_import_view.xml
  setup/l10n_th_base_location/odoo/addons/l10n_th_base_location
  setup/l10n_th_base_location/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#302 [15.0][MIG] l10n_th_partner
  l10n_th_partner/README.rst
  l10n_th_partner/__init__.py
  l10n_th_partner/__manifest__.py
  l10n_th_partner/data/res.partner.company.type.csv
  l10n_th_partner/data/res.partner.title.csv
  l10n_th_partner/hooks.py
  l10n_th_partner/i18n/en_US.po
  l10n_th_partner/i18n/l10n_th_partner.pot
  l10n_th_partner/i18n/th.po
  l10n_th_partner/i18n/th_TH.po
  l10n_th_partner/models/__init__.py
  l10n_th_partner/models/hr_employee.py
  l10n_th_partner/models/ir_translation.py
  l10n_th_partner/models/res_company.py
  l10n_th_partner/models/res_config_settings.py
  l10n_th_partner/models/res_partner.py
  l10n_th_partner/models/res_partner_company_type.py
  l10n_th_partner/models/resource.py
  l10n_th_partner/readme/CONTRIBUTORS.rst
  l10n_th_partner/readme/DESCRIPTION.rst
  l10n_th_partner/readme/HISTORY.rst
  l10n_th_partner/static/description/icon.png
  l10n_th_partner/static/description/index.html
  l10n_th_partner/tests/__init__.py
  l10n_th_partner/tests/test_l10n_th_partner.py
  l10n_th_partner/views/res_company_view.xml
  l10n_th_partner/views/res_config_settings_views.xml
  l10n_th_partner/views/res_partner_company_type_view.xml
  l10n_th_partner/views/res_partner_view.xml
  l10n_th_partner/views/res_users_view.xml
  setup/l10n_th_partner/odoo/addons/l10n_th_partner
  setup/l10n_th_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳
