Repository OCA/l10n-thailand, pull requests merged in 2023-11, with the labels that each got.

#336 [15.0][ADD] l10n_th_gov_hr_expense
  l10n_th_gov_hr_expense/README.rst
  l10n_th_gov_hr_expense/__init__.py
  l10n_th_gov_hr_expense/__manifest__.py
  l10n_th_gov_hr_expense/models/__init__.py
  l10n_th_gov_hr_expense/models/account_move.py
  l10n_th_gov_hr_expense/models/hr_expense.py
  l10n_th_gov_hr_expense/models/purchase_request.py
  l10n_th_gov_hr_expense/readme/CONFIGURE.rst
  l10n_th_gov_hr_expense/readme/CONTRIBUTORS.rst
  l10n_th_gov_hr_expense/readme/DESCRIPTION.rst
  l10n_th_gov_hr_expense/security/ir.model.access.csv
  l10n_th_gov_hr_expense/static/description/icon.png
  l10n_th_gov_hr_expense/static/description/index.html
  l10n_th_gov_hr_expense/tests/__init__.py
  l10n_th_gov_hr_expense/tests/test_gov_hr_expense.py
  l10n_th_gov_hr_expense/views/account_move_views.xml
  l10n_th_gov_hr_expense/views/hr_expense_views.xml
  l10n_th_gov_hr_expense/views/purchase_request_views.xml
  l10n_th_gov_hr_expense/views/reminder_definition_view.xml
  setup/l10n_th_gov_hr_expense/odoo/addons/l10n_th_gov_hr_expense
  setup/l10n_th_gov_hr_expense/setup.py
Labels: approved, bot is merging ⏳

#410 [15.0][FIX] *: test script change to setupClass
  currency_rate_update_TH_BOT/tests/test_currency_rate_update_TH_BOT.py
  l10n_th_account_tax/tests/test_withholding_tax_pit.py
  l10n_th_account_tax_expense/tests/test_expense_tax_invoice.py
  l10n_th_bank_payment_export/tests/common.py
  l10n_th_bank_payment_export/tests/test_bank_payment_export.py
  l10n_th_bank_payment_export_ktb/tests/test_bank_payment_export_ktb.py
  l10n_th_base_location/tests/test_base_location.py
  l10n_th_gov_hr_expense/models/hr_expense.py
  l10n_th_gov_purchase_agreement/tests/test_gov_purchase_agreement.py
  l10n_th_gov_purchase_guarantee/tests/test_purchase_guarantee.py
  l10n_th_gov_purchase_request/tests/test_gov_purchase_request.py
  l10n_th_gov_work_acceptance/tests/test_gov_purchase_work_acceptance.py
  l10n_th_partner/tests/test_l10n_th_partner.py
Labels: bot is merging ⏳

#357 [15.0][ADD] l10n_th_tier_department / l10n_th_tier_department_demo
  l10n_th_tier_department/README.rst
  l10n_th_tier_department/__init__.py
  l10n_th_tier_department/__manifest__.py
  l10n_th_tier_department/models/__init__.py
  l10n_th_tier_department/models/hr_department.py
  l10n_th_tier_department/models/tier_level.py
  l10n_th_tier_department/readme/CONTRIBUTORS.rst
  l10n_th_tier_department/readme/DESCRIPTION.rst
  l10n_th_tier_department/readme/USAGE.rst
  l10n_th_tier_department/security/ir.model.access.csv
  l10n_th_tier_department/security/tier_validation_department_security.xml
  l10n_th_tier_department/static/description/icon.png
  l10n_th_tier_department/static/description/index.html
  l10n_th_tier_department/templates/tier_validation_templates.xml
  l10n_th_tier_department/tests/__init__.py
  l10n_th_tier_department/tests/test_tier_validation_department.py
  l10n_th_tier_department/views/hr_department_views.xml
  l10n_th_tier_department/views/tier_level_views.xml
  l10n_th_tier_department_demo/README.rst
  l10n_th_tier_department_demo/__init__.py
  l10n_th_tier_department_demo/__manifest__.py
  l10n_th_tier_department_demo/data/hr_expense_tier_definition.xml
  l10n_th_tier_department_demo/data/purchase_request_tier_definition.xml
  l10n_th_tier_department_demo/readme/CONTRIBUTORS.rst
  l10n_th_tier_department_demo/readme/DESCRIPTION.rst
  l10n_th_tier_department_demo/static/description/icon.png
  l10n_th_tier_department_demo/static/description/index.html
  setup/l10n_th_tier_department/odoo/addons/l10n_th_tier_department
  setup/l10n_th_tier_department/setup.py
  setup/l10n_th_tier_department_demo/odoo/addons/l10n_th_tier_department_demo
  setup/l10n_th_tier_department_demo/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#413 [15.0][FIX] l10n_th_account_tax: hide WHT table
  l10n_th_account_tax/views/account_payment_view.xml
Labels: approved, bot is merging ⏳

#412 [15.0][FIX] l10n_th_account_tax_report: query mistake
  l10n_th_account_tax_report/reports/tax_report.py
Labels: approved, ready to merge, bot is merging ⏳

#402 [15.0][ENH] l10n_th_account_tax: add tax number in refund, sign of undue
  l10n_th_account_tax/__manifest__.py
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/withholding_tax_cert.py
  l10n_th_account_tax/tests/test_tax_invoice.py
  l10n_th_account_tax/tests/test_withholding_tax_pit.py
  l10n_th_account_tax/wizard/__init__.py
  l10n_th_account_tax/wizard/account_move_reversal.py
  l10n_th_account_tax/wizard/account_move_reversal_view.xml
  l10n_th_account_tax/wizard/account_payment_register.py
Labels: bot is merging ⏳

#403 [15.0][ENH] l10n_th_account_tax_report: support Paid Continuously on WHT
  l10n_th_account_tax_report/reports/report_withholding_tax.py
Labels: bot is merging ⏳

#383 [15.0][ADD] l10n_th_multicurrency_revaluation
  l10n_th_multicurrency_revaluation/README.rst
  l10n_th_multicurrency_revaluation/__init__.py
  l10n_th_multicurrency_revaluation/__manifest__.py
  l10n_th_multicurrency_revaluation/models/__init__.py
  l10n_th_multicurrency_revaluation/models/account_account.py
  l10n_th_multicurrency_revaluation/models/account_move.py
  l10n_th_multicurrency_revaluation/models/res_company.py
  l10n_th_multicurrency_revaluation/models/res_config.py
  l10n_th_multicurrency_revaluation/readme/CONFIGURE.rst
  l10n_th_multicurrency_revaluation/readme/CONTRIBUTORS.rst
  l10n_th_multicurrency_revaluation/readme/DESCRIPTION.rst
  l10n_th_multicurrency_revaluation/readme/USAGE.rst
  l10n_th_multicurrency_revaluation/report/__init__.py
  l10n_th_multicurrency_revaluation/report/currency_unrealized_report.py
  l10n_th_multicurrency_revaluation/report/currency_unrealized_report_xlsx.py
  l10n_th_multicurrency_revaluation/report/report.xml
  l10n_th_multicurrency_revaluation/report/unrealized_currency_gain_loss.xml
  l10n_th_multicurrency_revaluation/security/ir.model.access.csv
  l10n_th_multicurrency_revaluation/security/security.xml
  l10n_th_multicurrency_revaluation/static/description/icon.png
  l10n_th_multicurrency_revaluation/static/description/index.html
  l10n_th_multicurrency_revaluation/static/src/scss/reports.scss
  l10n_th_multicurrency_revaluation/tests/__init__.py
  l10n_th_multicurrency_revaluation/tests/test_multicurrency_revaluation.py
  l10n_th_multicurrency_revaluation/views/account_move_line_views.xml
  l10n_th_multicurrency_revaluation/views/account_move_views.xml
  l10n_th_multicurrency_revaluation/views/account_view.xml
  l10n_th_multicurrency_revaluation/views/res_config_view.xml
  l10n_th_multicurrency_revaluation/wizard/__init__.py
  l10n_th_multicurrency_revaluation/wizard/print_currency_unrealized_report.py
  l10n_th_multicurrency_revaluation/wizard/print_currency_unrealized_report_view.xml
  l10n_th_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
  l10n_th_multicurrency_revaluation/wizard/wizard_currency_revaluation_view.xml
  l10n_th_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation.py
  l10n_th_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation_view.xml
  setup/l10n_th_multicurrency_revaluation/odoo/addons/l10n_th_multicurrency_revaluation
  setup/l10n_th_multicurrency_revaluation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#406 [15.0][ADD] l10n_th_multicurrency_revaluation_operating_unit
  l10n_th_multicurrency_revaluation_operating_unit/README.rst
  l10n_th_multicurrency_revaluation_operating_unit/__init__.py
  l10n_th_multicurrency_revaluation_operating_unit/__manifest__.py
  l10n_th_multicurrency_revaluation_operating_unit/readme/CONTRIBUTORS.rst
  l10n_th_multicurrency_revaluation_operating_unit/readme/DESCRIPTION.rst
  l10n_th_multicurrency_revaluation_operating_unit/readme/USAGE.rst
  l10n_th_multicurrency_revaluation_operating_unit/static/description/index.html
  l10n_th_multicurrency_revaluation_operating_unit/wizard/__init__.py
  l10n_th_multicurrency_revaluation_operating_unit/wizard/wizard_currency_revaluation.py
  setup/l10n_th_multicurrency_revaluation_operating_unit/odoo/addons/l10n_th_multicurrency_revaluation_operating_unit
  setup/l10n_th_multicurrency_revaluation_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#394 [16.0][MIG] l10n_th_account_tax
  l10n_th_account_tax/README.rst
  l10n_th_account_tax/__init__.py
  l10n_th_account_tax/__manifest__.py
  l10n_th_account_tax/data/pit_rate_data.xml
  l10n_th_account_tax/data/withholding_tax_type_income_data.xml
  l10n_th_account_tax/i18n/l10n_th_account_tax.pot
  l10n_th_account_tax/models/__init__.py
  l10n_th_account_tax/models/account.py
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_move_tax_invoice.py
  l10n_th_account_tax/models/account_partial_reconcile.py
  l10n_th_account_tax/models/account_payment.py
  l10n_th_account_tax/models/account_tax.py
  l10n_th_account_tax/models/account_withholding_move.py
  l10n_th_account_tax/models/account_withholding_tax.py
  l10n_th_account_tax/models/personal_income_tax.py
  l10n_th_account_tax/models/product.py
  l10n_th_account_tax/models/res_company.py
  l10n_th_account_tax/models/res_config_settings.py
  l10n_th_account_tax/models/res_partner.py
  l10n_th_account_tax/models/withholding_tax_cert.py
  l10n_th_account_tax/readme/CONFIGURE.rst
  l10n_th_account_tax/readme/CONTRIBUTORS.rst
  l10n_th_account_tax/readme/DESCRIPTION.rst
  l10n_th_account_tax/readme/USAGE.rst
  l10n_th_account_tax/security/account_security.xml
  l10n_th_account_tax/security/ir.model.access.csv
  l10n_th_account_tax/static/description/icon.png
  l10n_th_account_tax/static/description/index.html
  l10n_th_account_tax/tests/__init__.py
  l10n_th_account_tax/tests/test_tax_invoice.py
  l10n_th_account_tax/tests/test_withholding_tax.py
  l10n_th_account_tax/tests/test_withholding_tax_pit.py
  l10n_th_account_tax/views/account_menu.xml
  l10n_th_account_tax/views/account_move_view.xml
  l10n_th_account_tax/views/account_payment_view.xml
  l10n_th_account_tax/views/account_tax_view.xml
  l10n_th_account_tax/views/account_view.xml
  l10n_th_account_tax/views/account_withholding_move.xml
  l10n_th_account_tax/views/account_withholding_tax.xml
  l10n_th_account_tax/views/personal_income_tax_view.xml
  l10n_th_account_tax/views/product_view.xml
  l10n_th_account_tax/views/res_config_settings_views.xml
  l10n_th_account_tax/views/res_partner_view.xml
  l10n_th_account_tax/views/withholding_tax_cert.xml
  l10n_th_account_tax/views/withholding_tax_code_income.xml
  l10n_th_account_tax/wizard/__init__.py
  l10n_th_account_tax/wizard/account_move_reversal.py
  l10n_th_account_tax/wizard/account_move_reversal_view.xml
  l10n_th_account_tax/wizard/account_payment_register.py
  l10n_th_account_tax/wizard/account_payment_register_views.xml
  setup/l10n_th_account_tax/odoo/addons/l10n_th_account_tax
  setup/l10n_th_account_tax/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#389 [16.0][MIG] l10n_th_base_location
  l10n_th_base_location/README.rst
  l10n_th_base_location/__init__.py
  l10n_th_base_location/__manifest__.py
  l10n_th_base_location/data/TH_en.txt
  l10n_th_base_location/data/TH_th.txt
  l10n_th_base_location/i18n/base_location_thailand.pot
  l10n_th_base_location/i18n/l10n_th_base_location.pot
  l10n_th_base_location/i18n/th.po
  l10n_th_base_location/models/__init__.py
  l10n_th_base_location/models/res_city_zip.py
  l10n_th_base_location/models/res_company.py
  l10n_th_base_location/models/res_country_state.py
  l10n_th_base_location/models/res_partner.py
  l10n_th_base_location/readme/CONTRIBUTORS.rst
  l10n_th_base_location/readme/CREDITS.rst
  l10n_th_base_location/readme/DESCRIPTION.rst
  l10n_th_base_location/readme/INSTALL.rst
  l10n_th_base_location/readme/USAGE.rst
  l10n_th_base_location/static/description/icon.png
  l10n_th_base_location/static/description/index.html
  l10n_th_base_location/tests/__init__.py
  l10n_th_base_location/tests/test_base_location.py
  l10n_th_base_location/views/res_city_zip_view.xml
  l10n_th_base_location/wizard/__init__.py
  l10n_th_base_location/wizard/geonames_import.py
  l10n_th_base_location/wizard/geonames_import_view.xml
  setup/l10n_th_base_location/odoo/addons/l10n_th_base_location
  setup/l10n_th_base_location/setup.py
Labels: approved, bot is merging ⏳
