Repository OCA/l10n-thailand, pull requests merged in 2023-10, with the labels that each got.

#361 [15.0][ADD] l10n_th_mis_report
  l10n_th_mis_report/README.rst
  l10n_th_mis_report/__init__.py
  l10n_th_mis_report/__manifest__.py
  l10n_th_mis_report/data/mis_report_bs.xml
  l10n_th_mis_report/data/mis_report_pl.xml
  l10n_th_mis_report/data/mis_report_style.xml
  l10n_th_mis_report/data/mis_report_tb.xml
  l10n_th_mis_report/readme/CONTRIBUTORS.rst
  l10n_th_mis_report/readme/DESCRIPTION.rst
  l10n_th_mis_report/static/description/icon.png
  l10n_th_mis_report/static/description/index.html
  setup/l10n_th_mis_report/odoo/addons/l10n_th_mis_report
  setup/l10n_th_mis_report/setup.py
Labels: approved, bot is merging ⏳

#399 [15.0][FIX] l10n_th_account_tax_report: RD Format PND1, 3, 53 multi line
  l10n_th_account_tax_report/reports/report_wht_qweb_rd.xml
  l10n_th_account_tax_report/reports/report_withholding_tax.py
Labels: approved, bot is merging ⏳

#396 [15.0][FIX] l10n_th_account_tax: can't reset payment with undue vat
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_partial_reconcile.py
  l10n_th_account_tax/models/account_payment.py
  l10n_th_account_tax/tests/test_tax_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#369 [15.0][REF] change name l10n_th_sequence_refactored -> l10n_th_base_sequence
  l10n_th_base_sequence/README.rst
  l10n_th_base_sequence/__init__.py
  l10n_th_base_sequence/__manifest__.py
  l10n_th_base_sequence/models/__init__.py
  l10n_th_base_sequence/models/ir_sequence.py
  l10n_th_base_sequence/models/ir_sequence_date_range.py
  l10n_th_base_sequence/readme/CONTRIBUTORS.rst
  l10n_th_base_sequence/readme/DESCRIPTION.rst
  l10n_th_base_sequence/static/description/icon.png
  l10n_th_base_sequence/static/description/index.html
  l10n_th_base_sequence/tests/__init__.py
  l10n_th_base_sequence/tests/test_ir_sequence.py
  l10n_th_base_sequence/tests/test_ir_sequence_date_range.py
  l10n_th_base_sequence/views/ir_sequence_view.xml
  l10n_th_sequence_refactored/i18n/l10n_th_sequence_refactored.pot
  l10n_th_sequence_refactored/readme/DESCRIPTION.rst
  l10n_th_sequence_refactored/tests/test_ir_sequence.py
  l10n_th_sequence_refactored/tests/test_ir_sequence_date_range.py
  l10n_th_sequence_refactored/views/ir_sequence_view.xml
  setup/l10n_th_base_sequence/odoo/addons/l10n_th_base_sequence
  setup/l10n_th_base_sequence/setup.py
  setup/l10n_th_sequence_refactored/odoo/addons/l10n_th_sequence_refactored
Labels: approved, ready to merge, bot is merging ⏳

#408 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: help wanted, needs review

#409 [15.0][FIX] pre-commit
  currency_rate_update_TH_BOT/models/res_currency_rate_provider_BOT.py
  l10n_th_account_tax/models/withholding_tax_cert.py
  l10n_th_gov_purchase_guarantee/models/purchase_guarantee.py
Labels: bot is merging ⏳
