Repository OCA/l10n-thailand, pull requests merged in 2023-09, with the labels that each got.

#351 [15.0][FIX] l10n_th_account_tax: allow duplicate PIT Table with other year
  l10n_th_account_tax/models/personal_income_tax.py
  l10n_th_account_tax/tests/test_withholding_tax_pit.py
  l10n_th_account_tax/views/personal_income_tax_view.xml
Labels: approved, bot is merging ⏳

#374 [15.0][FIX] l10n_th_account_tax: fix bug space table and copy PIT line is not correct
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#362 [15.0][FIX] l10n_th_account_tax: allow reconcile undue case can't register payment
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_partial_reconcile.py
  l10n_th_account_tax/models/account_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#386 [15.0][ENH] l10n_th_account_tax: auto change report tax late when accounting date and tax invoice date is not a same month
  l10n_th_account_tax/models/account_move_tax_invoice.py
  l10n_th_account_tax/views/account_move_view.xml
  l10n_th_account_tax/views/account_payment_view.xml
Labels: approved, bot is merging ⏳

#381 [15.0][ENH] l10n_th_account_tax: split default vendor WHT for individual and company
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/product.py
  l10n_th_account_tax/tests/test_withholding_tax.py
  l10n_th_account_tax/views/product_view.xml
Labels: approved, bot is merging ⏳

#377 [15.0][ENH] l10n_th_account_tax: default value to WHT Certs.
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_withholding_move.py
  l10n_th_account_tax/models/account_withholding_tax.py
  l10n_th_account_tax/views/account_withholding_tax.xml
Labels: approved, bot is merging ⏳

#337 [15.0][MIG] l10n_th_gov_work_acceptance
  l10n_th_gov_work_acceptance/README.rst
  l10n_th_gov_work_acceptance/__init__.py
  l10n_th_gov_work_acceptance/__manifest__.py
  l10n_th_gov_work_acceptance/data/evaluation_data.xml
  l10n_th_gov_work_acceptance/data/server_action.xml
  l10n_th_gov_work_acceptance/data/tier.definition.csv
  l10n_th_gov_work_acceptance/i18n/l10n_th_gov_work_acceptance.pot
  l10n_th_gov_work_acceptance/models/__init__.py
  l10n_th_gov_work_acceptance/models/purchase.py
  l10n_th_gov_work_acceptance/models/tier_validation.py
  l10n_th_gov_work_acceptance/models/work_acceptance.py
  l10n_th_gov_work_acceptance/models/work_acceptance_committee.py
  l10n_th_gov_work_acceptance/readme/CONTRIBUTORS.rst
  l10n_th_gov_work_acceptance/readme/DESCRIPTION.rst
  l10n_th_gov_work_acceptance/security/ir.model.access.csv
  l10n_th_gov_work_acceptance/static/description/icon.png
  l10n_th_gov_work_acceptance/static/description/index.html
  l10n_th_gov_work_acceptance/tests/__init__.py
  l10n_th_gov_work_acceptance/tests/test_gov_purchase_work_acceptance.py
  l10n_th_gov_work_acceptance/views/purchase_views.xml
  l10n_th_gov_work_acceptance/views/work_acceptance_views.xml
  setup/l10n_th_gov_work_acceptance/odoo/addons/l10n_th_gov_work_acceptance
  setup/l10n_th_gov_work_acceptance/setup.py
Labels: approved, bot is merging ⏳

#376 [15.0][ENH] l10n_th_partner: check duplicate vat and branch
  l10n_th_partner/models/res_partner.py
  l10n_th_partner/tests/test_l10n_th_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#387 [15.0][FIX] l10n_th_account_tax: add domain purchase taxes with type_tax_use
  l10n_th_account_tax/models/account_move.py
Labels: approved, bot is merging ⏳

#380 [15.0][ADD] currency_rate_update_TH_BOT
  currency_rate_update_TH_BOT/README.rst
  currency_rate_update_TH_BOT/__init__.py
  currency_rate_update_TH_BOT/__manifest__.py
  currency_rate_update_TH_BOT/data/config_parameter.xml
  currency_rate_update_TH_BOT/models/__init__.py
  currency_rate_update_TH_BOT/models/res_company.py
  currency_rate_update_TH_BOT/models/res_config_settings.py
  currency_rate_update_TH_BOT/models/res_currency.py
  currency_rate_update_TH_BOT/models/res_currency_rate_provider_BOT.py
  currency_rate_update_TH_BOT/readme/CONFIGURE.rst
  currency_rate_update_TH_BOT/readme/CONTRIBUTORS.rst
  currency_rate_update_TH_BOT/readme/DESCRIPTION.rst
  currency_rate_update_TH_BOT/readme/USAGE.rst
  currency_rate_update_TH_BOT/static/description/icon.png
  currency_rate_update_TH_BOT/static/description/index.html
  currency_rate_update_TH_BOT/tests/__init__.py
  currency_rate_update_TH_BOT/tests/test_currency_rate_update_TH_BOT.py
  currency_rate_update_TH_BOT/views/res_config_settings.xml
  currency_rate_update_TH_BOT/views/res_currency_rate_provider.xml
  currency_rate_update_TH_BOT/views/res_currency_views.xml
  setup/currency_rate_update_TH_BOT/odoo/addons/currency_rate_update_TH_BOT
  setup/currency_rate_update_TH_BOT/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#360 [15.0][ENH] l10n_th_account_asset_management: add parent asset
  l10n_th_account_asset_management/__init__.py
  l10n_th_account_asset_management/__manifest__.py
  l10n_th_account_asset_management/data/account_asset_parent_data.xml
  l10n_th_account_asset_management/data/account_asset_sub_state_data.xml
  l10n_th_account_asset_management/models/__init__.py
  l10n_th_account_asset_management/models/account_asset.py
  l10n_th_account_asset_management/models/account_asset_parent.py
  l10n_th_account_asset_management/models/account_asset_sub_state.py
  l10n_th_account_asset_management/readme/DESCRIPTION.rst
  l10n_th_account_asset_management/security/ir.model.access.csv
  l10n_th_account_asset_management/tests/test_account_asset_management.py
  l10n_th_account_asset_management/views/account_asset_parent_views.xml
  l10n_th_account_asset_management/views/account_asset_sub_state_views.xml
  l10n_th_account_asset_management/views/account_asset_views.xml
  l10n_th_account_asset_management/wizard/__init__.py
  l10n_th_account_asset_management/wizard/account_asset_remove.py
  l10n_th_account_asset_management/wizard/account_asset_remove.xml
  l10n_th_account_asset_management/wizard/account_asset_transfer.py
  l10n_th_account_asset_management/wizard/account_asset_transfer.xml
Labels: approved, bot is merging ⏳

#352 [15.0][FIX] l10n_th_account_tax: fix sign tax invoice refund
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_move_tax_invoice.py
  l10n_th_account_tax/models/account_partial_reconcile.py
  l10n_th_account_tax/tests/test_tax_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#388 [15.0][FIX] l10n_th_account_tax_multi: Error register payment when select multiple vendor bills
  l10n_th_account_tax_multi/__init__.py
  l10n_th_account_tax_multi/models/__init__.py
  l10n_th_account_tax_multi/models/account_move.py
  l10n_th_account_tax_multi/wizard/account_payment_deduction.py
  l10n_th_account_tax_multi/wizard/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#358 [15.0][IMP] l10n_th_gov_account_asset_management: add fields, change display name
  l10n_th_gov_account_asset_management/__manifest__.py
  l10n_th_gov_account_asset_management/data/ir_actions_server_data.xml
  l10n_th_gov_account_asset_management/models/__init__.py
  l10n_th_gov_account_asset_management/models/account_asset.py
  l10n_th_gov_account_asset_management/models/account_asset_line.py
  l10n_th_gov_account_asset_management/models/account_asset_location.py
  l10n_th_gov_account_asset_management/models/account_asset_maintenance.py
  l10n_th_gov_account_asset_management/models/account_move.py
  l10n_th_gov_account_asset_management/models/purchase.py
  l10n_th_gov_account_asset_management/readme/CONTRIBUTORS.rst
  l10n_th_gov_account_asset_management/readme/DESCRIPTION.rst
  l10n_th_gov_account_asset_management/readme/HISTORY.rst
  l10n_th_gov_account_asset_management/security/ir.model.access.csv
  l10n_th_gov_account_asset_management/static/description/index.html
  l10n_th_gov_account_asset_management/tests/test_gov_account_asset_management.py
  l10n_th_gov_account_asset_management/views/account_asset_location_views.xml
  l10n_th_gov_account_asset_management/views/account_asset_views.xml
  l10n_th_gov_account_asset_management/views/account_move.xml
  l10n_th_gov_account_asset_management/views/purchase_views.xml
  l10n_th_gov_account_asset_management/wizard/__init__.py
  l10n_th_gov_account_asset_management/wizard/account_asset_remove.py
  l10n_th_gov_account_asset_management/wizard/account_asset_transfer.py
Labels: approved, bot is merging ⏳

#371 [15.0][FIX] l10n_th_account_tax_expense: readonly fields following standard fields
  l10n_th_account_tax_expense/views/hr_expense_view.xml
Labels: approved, bot is merging ⏳

#315 [16.0][MIG] l10n_th_amount_to_text
  l10n_th_amount_to_text/README.rst
  l10n_th_amount_to_text/__init__.py
  l10n_th_amount_to_text/__manifest__.py
  l10n_th_amount_to_text/i18n/l10n_th_amount_to_text.pot
  l10n_th_amount_to_text/i18n/th.po
  l10n_th_amount_to_text/models/__init__.py
  l10n_th_amount_to_text/models/res_currency.py
  l10n_th_amount_to_text/readme/CONFIGURE.rst
  l10n_th_amount_to_text/readme/CONTRIBUTORS.rst
  l10n_th_amount_to_text/readme/DESCRIPTION.rst
  l10n_th_amount_to_text/readme/USAGE.rst
  l10n_th_amount_to_text/static/description/icon.png
  l10n_th_amount_to_text/static/description/index.html
  l10n_th_amount_to_text/tests/__init__.py
  l10n_th_amount_to_text/tests/test_amount_to_text.py
  requirements.txt
  setup/l10n_th_amount_to_text/odoo/addons/l10n_th_amount_to_text
  setup/l10n_th_amount_to_text/setup.py
Labels: approved, bot is merging ⏳, stale
