Repository OCA/l10n-thailand, pull requests merged in 2024-07, with the labels that each got.

#431 [15.0][ENH] l10n_th_account_tax_expense: send sequence expense to move
  l10n_th_account_tax_expense/README.rst
  l10n_th_account_tax_expense/__manifest__.py
  l10n_th_account_tax_expense/models/hr_expense.py
  l10n_th_account_tax_expense/static/description/index.html
Labels: bot is merging ⏳

#457 [15.0][ENH] l10n_th_account_tax: multi-company
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_withholding_move.py
  l10n_th_account_tax/models/account_withholding_tax.py
  l10n_th_account_tax/models/product.py
  l10n_th_account_tax/models/withholding_tax_cert.py
  l10n_th_account_tax/security/account_security.xml
  l10n_th_account_tax/views/account_withholding_move.xml
  l10n_th_account_tax/views/account_withholding_tax.xml
  l10n_th_account_tax/views/withholding_tax_cert.xml
  l10n_th_account_tax/wizard/account_payment_register.py
Labels: approved, bot is merging ⏳

#378 [16.0][MIG] l10n_th_promptpay
  l10n_th_promptpay/README.rst
  l10n_th_promptpay/__init__.py
  l10n_th_promptpay/__manifest__.py
  l10n_th_promptpay/data/payment_icon_data.xml
  l10n_th_promptpay/i18n/l10n_th_promptpay.pot
  l10n_th_promptpay/i18n/th_TH.po
  l10n_th_promptpay/models/__init__.py
  l10n_th_promptpay/models/payment_provider.py
  l10n_th_promptpay/readme/CONTRIBUTORS.rst
  l10n_th_promptpay/readme/CREDITS.rst
  l10n_th_promptpay/readme/DESCRIPTION.rst
  l10n_th_promptpay/readme/HISTORY.rst
  l10n_th_promptpay/readme/USAGE.rst
  l10n_th_promptpay/static/description/icon.png
  l10n_th_promptpay/static/description/index.html
  l10n_th_promptpay/static/description/promptpay_QR_code.png
  l10n_th_promptpay/static/description/promptpay_configuration.png
  l10n_th_promptpay/static/description/website_confirm_order.png
  l10n_th_promptpay/static/img/baac.png
  l10n_th_promptpay/static/img/bay.png
  l10n_th_promptpay/static/img/bbl.png
  l10n_th_promptpay/static/img/bnp.png
  l10n_th_promptpay/static/img/boa.png
  l10n_th_promptpay/static/img/cacib.png
  l10n_th_promptpay/static/img/cimb.png
  l10n_th_promptpay/static/img/citi.png
  l10n_th_promptpay/static/img/db.png
  l10n_th_promptpay/static/img/ghb.png
  l10n_th_promptpay/static/img/gsb.png
  l10n_th_promptpay/static/img/hsbc.png
  l10n_th_promptpay/static/img/ibank.png
  l10n_th_promptpay/static/img/icbc.png
  l10n_th_promptpay/static/img/jpm.png
  l10n_th_promptpay/static/img/kbank.png
  l10n_th_promptpay/static/img/kk.png
  l10n_th_promptpay/static/img/ktb.png
  l10n_th_promptpay/static/img/lhb.png
  l10n_th_promptpay/static/img/mb.png
  l10n_th_promptpay/static/img/mega.png
  l10n_th_promptpay/static/img/mufg.png
  l10n_th_promptpay/static/img/promptpay_logo.png
  l10n_th_promptpay/static/img/rbs.png
  l10n_th_promptpay/static/img/sc.png
  l10n_th_promptpay/static/img/scb.png
  l10n_th_promptpay/static/img/smbc.png
  l10n_th_promptpay/static/img/tbank.png
  l10n_th_promptpay/static/img/tcrb.png
  l10n_th_promptpay/static/img/thai_qr_payment.png
  l10n_th_promptpay/static/img/tisco.png
  l10n_th_promptpay/static/img/tmb.png
  l10n_th_promptpay/static/img/uob.png
  l10n_th_promptpay/tests/__init__.py
  l10n_th_promptpay/tests/test_promptpay.py
  l10n_th_promptpay/views/payment_transfer_acquirer_form.xml
  l10n_th_promptpay/views/payment_views.xml
  requirements.txt
  setup/l10n_th_promptpay/odoo/addons/l10n_th_promptpay
  setup/l10n_th_promptpay/setup.py
Labels: bot is merging ⏳, stale

#466 [16.0][MIG] l10n_th_base_sequence: Migration to 16.0
  l10n_th_base_sequence/README.rst
  l10n_th_base_sequence/__init__.py
  l10n_th_base_sequence/__manifest__.py
  l10n_th_base_sequence/i18n/l10n_th_base_sequence.pot
  l10n_th_base_sequence/models/__init__.py
  l10n_th_base_sequence/models/ir_sequence.py
  l10n_th_base_sequence/models/ir_sequence_date_range.py
  l10n_th_base_sequence/readme/CONTRIBUTORS.rst
  l10n_th_base_sequence/readme/DESCRIPTION.rst
  l10n_th_base_sequence/static/description/icon.png
  l10n_th_base_sequence/static/description/index.html
  l10n_th_base_sequence/tests/__init__.py
  l10n_th_base_sequence/tests/test_ir_sequence.py
  l10n_th_base_sequence/tests/test_ir_sequence_date_range.py
  l10n_th_base_sequence/views/ir_sequence_view.xml
  setup/l10n_th_base_sequence/odoo/addons/l10n_th_base_sequence
  setup/l10n_th_base_sequence/setup.py
Labels: bot is merging ⏳
