Repository OCA/l10n-thailand, pull requests merged in 2025-02, with the labels that each got.

#507 [15.0][FIX] l10n_th_account_tax: Skip error when unreconcile tax cash basis
  l10n_th_account_tax/models/account_move.py
Labels: approved, bot is merging ⏳

#505 [15.0][FIX] l10n_th_gov_hr_expense: split function
  l10n_th_gov_hr_expense/models/hr_expense.py
Labels: approved, ready to merge, bot is merging ⏳

#508 [16.0][FIX] l10n_th_tax_address: Call API with SOAP payload
  l10n_th_tax_address/data/ir_config_parameter.xml
  l10n_th_tax_address/models/res_partner.py
  l10n_th_tax_address/tests/test_l10n_th_tax_address.py
Labels: approved, bot is merging ⏳

#480 [17.0][MIG] currency_rate_update_TH_BOT
  currency_rate_update_TH_BOT/README.rst
  currency_rate_update_TH_BOT/__init__.py
  currency_rate_update_TH_BOT/__manifest__.py
  currency_rate_update_TH_BOT/data/config_parameter.xml
  currency_rate_update_TH_BOT/i18n/currency_rate_update_TH_BOT.pot
  currency_rate_update_TH_BOT/models/__init__.py
  currency_rate_update_TH_BOT/models/res_company.py
  currency_rate_update_TH_BOT/models/res_config_settings.py
  currency_rate_update_TH_BOT/models/res_currency.py
  currency_rate_update_TH_BOT/models/res_currency_rate_provider_BOT.py
  currency_rate_update_TH_BOT/pyproject.toml
  currency_rate_update_TH_BOT/readme/CONFIGURE.md
  currency_rate_update_TH_BOT/readme/CONTRIBUTORS.md
  currency_rate_update_TH_BOT/readme/DESCRIPTION.md
  currency_rate_update_TH_BOT/readme/USAGE.md
  currency_rate_update_TH_BOT/static/description/icon.png
  currency_rate_update_TH_BOT/static/description/index.html
  currency_rate_update_TH_BOT/tests/__init__.py
  currency_rate_update_TH_BOT/tests/test_currency_rate_update_TH_BOT.py
  currency_rate_update_TH_BOT/views/res_config_settings.xml
  currency_rate_update_TH_BOT/views/res_currency_rate_provider.xml
  currency_rate_update_TH_BOT/views/res_currency_views.xml
Labels: approved, bot is merging ⏳

#504 [17.0][MIG] l10n_th_base_sequence: Migration to 17.0
  l10n_th_base_sequence/README.rst
  l10n_th_base_sequence/__init__.py
  l10n_th_base_sequence/__manifest__.py
  l10n_th_base_sequence/i18n/l10n_th_base_sequence.pot
  l10n_th_base_sequence/models/__init__.py
  l10n_th_base_sequence/models/ir_sequence.py
  l10n_th_base_sequence/models/ir_sequence_date_range.py
  l10n_th_base_sequence/pyproject.toml
  l10n_th_base_sequence/readme/CONTRIBUTORS.md
  l10n_th_base_sequence/readme/DESCRIPTION.md
  l10n_th_base_sequence/static/description/icon.png
  l10n_th_base_sequence/static/description/index.html
  l10n_th_base_sequence/tests/__init__.py
  l10n_th_base_sequence/tests/test_ir_sequence.py
  l10n_th_base_sequence/tests/test_ir_sequence_date_range.py
  l10n_th_base_sequence/views/ir_sequence_view.xml
Labels: approved, bot is merging ⏳

#486 [18.0][MIG] l10n_th_amount_to_text
  l10n_th_amount_to_text/README.rst
  l10n_th_amount_to_text/__init__.py
  l10n_th_amount_to_text/__manifest__.py
  l10n_th_amount_to_text/i18n/l10n_th_amount_to_text.pot
  l10n_th_amount_to_text/i18n/th.po
  l10n_th_amount_to_text/models/__init__.py
  l10n_th_amount_to_text/models/res_currency.py
  l10n_th_amount_to_text/pyproject.toml
  l10n_th_amount_to_text/readme/CONTRIBUTORS.md
  l10n_th_amount_to_text/readme/DESCRIPTION.md
  l10n_th_amount_to_text/readme/USAGE.md
  l10n_th_amount_to_text/static/description/icon.png
  l10n_th_amount_to_text/static/description/index.html
  l10n_th_amount_to_text/tests/__init__.py
  l10n_th_amount_to_text/tests/test_amount_to_text.py
Labels: approved, bot is merging ⏳

#483 [17.0][MIG] l10n_th_tier_department_demo
  l10n_th_tier_department_demo/README.rst
  l10n_th_tier_department_demo/__init__.py
  l10n_th_tier_department_demo/__manifest__.py
  l10n_th_tier_department_demo/data/hr_expense_tier_definition.xml
  l10n_th_tier_department_demo/data/purchase_request_tier_definition.xml
  l10n_th_tier_department_demo/i18n/l10n_th_tier_department_demo.pot
  l10n_th_tier_department_demo/pyproject.toml
  l10n_th_tier_department_demo/readme/CONTRIBUTORS.md
  l10n_th_tier_department_demo/readme/DESCRIPTION.md
  l10n_th_tier_department_demo/static/description/icon.png
  l10n_th_tier_department_demo/static/description/index.html
Labels: approved, bot is merging ⏳

#478 [16.0][FIX] l10n_th_account_tax: create wht move only for journal item with a wht id
  l10n_th_account_tax/models/account_move.py
Labels: bot is merging ⏳
