Repository OCA/l10n-thailand, pull requests merged in 2025-08, with the labels that each got.

#537 [15.0][IMP] currency_rate_update_TH_BOT : single_unit_currency_conversion
  currency_rate_update_TH_BOT/models/res_currency_rate_provider_BOT.py
Labels: bot is merging ⏳

#538 [18.0][FIX] l10n_th_account_tax: Create cash basis without sequence
  l10n_th_account_tax/models/account_move.py
  l10n_th_account_tax/models/account_partial_reconcile.py
  l10n_th_account_tax/tests/test_tax_invoice.py
Labels: approved, bot is merging ⏳

#536 [15.0][FIX] l10n_th_account_tax: Update tax invoice on manual reconcile
  l10n_th_account_tax/models/account_move.py
Labels: approved, bot is merging ⏳

#539 [18.0][FIX] l10n_th_account_tax: Update tax invoice on manual reconcile
  l10n_th_account_tax/models/account_move.py
Labels: bot is merging ⏳

#531 [18.0][IMP] l10n_th_fonts -> l10n_th_base_utils: add utils function convert to thai
  l10n_th_base_utils/README.rst
  l10n_th_base_utils/__init__.py
  l10n_th_base_utils/__manifest__.py
  l10n_th_base_utils/models/__init__.py
  l10n_th_base_utils/models/res_company.py
  l10n_th_base_utils/models/thai_utils.py
  l10n_th_base_utils/pyproject.toml
  l10n_th_base_utils/readme/CONFIGURE.md
  l10n_th_base_utils/readme/CONTRIBUTORS.md
  l10n_th_base_utils/readme/DESCRIPTION.md
  l10n_th_base_utils/readme/USAGE.md
  l10n_th_base_utils/static/description/icon.png
  l10n_th_base_utils/static/description/index.html
  l10n_th_base_utils/static/fonts/AngsanaNew.ttf
  l10n_th_base_utils/static/fonts/THBaijam.ttf
  l10n_th_base_utils/static/fonts/THChakraPetch.ttf
  l10n_th_base_utils/static/fonts/THCharmofAU.ttf
  l10n_th_base_utils/static/fonts/THCharmonman.ttf
  l10n_th_base_utils/static/fonts/THFahkwang.ttf
  l10n_th_base_utils/static/fonts/THK2DJuly8.ttf
  l10n_th_base_utils/static/fonts/THKoHo.ttf
  l10n_th_base_utils/static/fonts/THKodchasal.ttf
  l10n_th_base_utils/static/fonts/THKrub.ttf
  l10n_th_base_utils/static/fonts/THMaliGrade6.ttf
  l10n_th_base_utils/static/fonts/THNiramitAS.ttf
  l10n_th_base_utils/static/fonts/THSarabun.ttf
  l10n_th_base_utils/static/fonts/THSarabunNew.ttf
  l10n_th_base_utils/static/fonts/THSrisakdi.ttf
  l10n_th_base_utils/static/fonts/Webdings.ttf
  l10n_th_base_utils/static/src/scss/fonts_style.scss
  l10n_th_base_utils/tests/__init__.py
  l10n_th_base_utils/tests/test_l10n_th_base_utils.py
  l10n_th_fonts/README.rst
  l10n_th_fonts/i18n/l10n_th_fonts.pot
  l10n_th_fonts/readme/CONFIGURE.md
  l10n_th_fonts/readme/DESCRIPTION.md
Labels: needs review, bot is merging ⏳

#489 [18.0][MIG] l10n_th_account_wht_cert_form
  l10n_th_account_wht_cert_form/README.rst
  l10n_th_account_wht_cert_form/__init__.py
  l10n_th_account_wht_cert_form/__manifest__.py
  l10n_th_account_wht_cert_form/data/mail_template.xml
  l10n_th_account_wht_cert_form/data/paper_format.xml
  l10n_th_account_wht_cert_form/data/withholding_tax_cert_data.xml
  l10n_th_account_wht_cert_form/i18n/l10n_th_account_wht_cert_form.pot
  l10n_th_account_wht_cert_form/models/__init__.py
  l10n_th_account_wht_cert_form/models/res_company.py
  l10n_th_account_wht_cert_form/models/res_config_settings.py
  l10n_th_account_wht_cert_form/models/withholding_tax_cert.py
  l10n_th_account_wht_cert_form/pyproject.toml
  l10n_th_account_wht_cert_form/readme/CONTRIBUTORS.md
  l10n_th_account_wht_cert_form/readme/DESCRIPTION.md
  l10n_th_account_wht_cert_form/readme/USAGE.md
  l10n_th_account_wht_cert_form/reports/withholding_tax_cert_form_view.xml
  l10n_th_account_wht_cert_form/static/description/icon.png
  l10n_th_account_wht_cert_form/static/description/index.html
  l10n_th_account_wht_cert_form/static/src/img/WithholdingCert.png
  l10n_th_account_wht_cert_form/static/src/scss/style_report.scss
  l10n_th_account_wht_cert_form/tests/__init__.py
  l10n_th_account_wht_cert_form/tests/test_wht_cert_form.py
  l10n_th_account_wht_cert_form/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#511 [18.0][MIG] l10n_th_account_tax_report
  l10n_th_account_tax_report/README.rst
  l10n_th_account_tax_report/__init__.py
  l10n_th_account_tax_report/__manifest__.py
  l10n_th_account_tax_report/data/paper_format.xml
  l10n_th_account_tax_report/data/report_data.xml
  l10n_th_account_tax_report/i18n/l10n_th_account_tax_report.pot
  l10n_th_account_tax_report/models/__init__.py
  l10n_th_account_tax_report/models/res_company.py
  l10n_th_account_tax_report/models/res_config_settings.py
  l10n_th_account_tax_report/pyproject.toml
  l10n_th_account_tax_report/readme/CONFIGURE.md
  l10n_th_account_tax_report/readme/CONTRIBUTORS.md
  l10n_th_account_tax_report/readme/DESCRIPTION.md
  l10n_th_account_tax_report/readme/USAGE.md
  l10n_th_account_tax_report/reports/__init__.py
  l10n_th_account_tax_report/reports/tax_report.py
  l10n_th_account_tax_report/reports/tax_report_rd.py
  l10n_th_account_tax_report/reports/tax_report_xlsx.py
  l10n_th_account_tax_report/reports/templates/tax_report.xml
  l10n_th_account_tax_report/reports/templates/tax_report_rd.xml
  l10n_th_account_tax_report/reports/templates/wht_report.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd_pnd1.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd_pnd1a.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd_pnd2.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd_pnd3.xml
  l10n_th_account_tax_report/reports/templates/wht_report_rd_pnd53.xml
  l10n_th_account_tax_report/reports/templates/wht_report_text.xml
  l10n_th_account_tax_report/reports/wht_report.py
  l10n_th_account_tax_report/reports/wht_report_rd.py
  l10n_th_account_tax_report/reports/wht_report_text.py
  l10n_th_account_tax_report/reports/wht_report_xlsx.py
  l10n_th_account_tax_report/security/ir.model.access.csv
  l10n_th_account_tax_report/static/description/icon.png
  l10n_th_account_tax_report/static/description/index.html
  l10n_th_account_tax_report/static/src/img/pnd1.png
  l10n_th_account_tax_report/static/src/img/pnd1_lastpage.png
  l10n_th_account_tax_report/static/src/img/pnd1a.png
  l10n_th_account_tax_report/static/src/img/pnd1a_lastpage.png
  l10n_th_account_tax_report/static/src/img/pnd2.png
  l10n_th_account_tax_report/static/src/img/pnd3.png
  l10n_th_account_tax_report/static/src/img/pnd3_lastpage.png
  l10n_th_account_tax_report/static/src/img/pnd53.png
  l10n_th_account_tax_report/static/src/img/pnd53_lastpage.png
  l10n_th_account_tax_report/static/src/scss/style_report.scss
  l10n_th_account_tax_report/tests/__init__.py
  l10n_th_account_tax_report/tests/test_tax_report.py
  l10n_th_account_tax_report/tests/test_wht_cert_report.py
  l10n_th_account_tax_report/views/account_menu.xml
  l10n_th_account_tax_report/views/res_company_views.xml
  l10n_th_account_tax_report/views/res_config_settings_views.xml
  l10n_th_account_tax_report/wizard/__init__.py
  l10n_th_account_tax_report/wizard/abstract_wizard.py
  l10n_th_account_tax_report/wizard/tax_report_wizard.py
  l10n_th_account_tax_report/wizard/tax_report_wizard_view.xml
  l10n_th_account_tax_report/wizard/withholding_tax_report_wizard.py
  l10n_th_account_tax_report/wizard/withholding_tax_report_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#549 [15.0][FIX] l10n_th_gov_hr_expense: compute clearing date due only advance
  l10n_th_gov_hr_expense/models/hr_expense.py
Labels: approved, bot is merging ⏳
